Added User Authenticator System for Issue #5
Anish-M-code/Leaky-LAN pull request #10
Opened 2023-10-07 20:00 UTC by bvks2020sameer

Hi according to the open issue of this project I have added the user authentication system file

2023-10-08 03:20 UTC, Anish-M-code commented
@bvks2020sameer the code looks good but it be be better if this code could could be integrated with existing leakylan code and i guess we dont need email and name , just an alphanumeric id and password. The password should be generated by python and displayed in commandline in server side. the user has to manually share the password with person who wants to send / recieve files.

2023-10-10 16:10 UTC, bvks2020sameer commented
Hi have made the changes

2023-10-12 17:04 UTC, Anish-M-code requested changes

2023-10-12 17:04 UTC, Anish-M-code commented on User_Authenticator.py
> +host = 'localhost'
Avoid hardcoding values , you can get input from user , From line 76 - 80 , there are many hardcoded values

2023-10-12 17:05 UTC, Anish-M-code commented
Also @bvks2020sameer avoid unnecessary blank lines , it feels odd.

2023-10-13 15:02 UTC, bvks2020sameer commented
The above mentioned changes have been done

2023-10-14 17:03 UTC, merged

2023-10-14 17:03 UTC, Anish-M-code commented
@bvks2020sameer thanks for contributing.

2023-10-14 17:04 UTC, bvks2020sameer commented
Thankyou. Looking more to collaborate on . Happy Hacking